name: SE333_CI

on:
  push:
    branches:
      - part1-task2

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      #  Static analysis in validate phase 
      - name: Run Checkstyle (validate phase)
        run: mvn validate checkstyle:checkstyle

      # Upload XML report 
      - name: Upload Checkstyle Result
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

      #  Run tests AFTER analysis
      - name: Run Maven Test
        run: mvn test

      # Generate coverage
      - name: Jacoco Report
        run: mvn jacoco:report

      # Upload XML coverage report
      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml